- hosts: docker
  become: yes
  tasks:
    - name: Pull latest Docker images
      shell: docker-compose pull
      args:
        chdir: /opt/docker

    - name: Restart Docker containers
      shell: docker-compose up -d
      args:
        chdir: /opt/docker
